---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc1
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi-hostpath-sc 
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc2
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: csi-hostpath-sc   
