apiVersion: volume.makro.com/v1alpha1
kind: PVCResize
metadata:
  labels:
    app.kubernetes.io/name: pvc-resizer-controller
    app.kubernetes.io/managed-by: kustomize
  name: pvcresize-sample
spec:
  # TODO(user): Add fields here
