apiVersion: volume.makro.com/v1alpha1
kind: PVCResize
metadata:
  labels:
    app.kubernetes.io/name: pvc-resizer-controller
    app.kubernetes.io/managed-by: kustomize
  name: sample1
spec:
  policies:
    - ref: csi-pvc1
      size: 5Gi
    - ref: csi-pvc2
      size: 3Gi  
